plugins {
    id 'java'
    id 'application'
    id 'checkstyle'
    id 'jacoco'
}

application {
    mainClass = 'com.fmi.myfitnesspal.cli.Main'
}

group = 'com.fmi'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

java {
    sourceCompatibility = 17
    targetCompatibility = 17
}

checkstyle {
    toolVersion '10.0'
    // This ensures Checkstyle doesn't stop the build locally if you want to see all errors
    ignoreFailures = false
    showViolations = true
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.9.1')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.mockito:mockito-core:5.11.0'
    testImplementation 'org.mockito:mockito-junit-jupiter:5.11.0'
    implementation 'org.knowm.xchart:xchart:3.8.1'
    implementation 'tools.jackson.core:jackson-databind:3.1.0'
}

run {
    standardInput = System.in
}

test {
    useJUnitPlatform()
    finalizedBy jacocoTestReport

    if (project.hasProperty('ciJacoco')) {
        ignoreFailures = true
    }
}

jacoco {
    toolVersion = "0.8.12"
}

def jacocoExcludes = [
        "**/Main.class",
        "org/external/**/*.class"
]

tasks.withType(JacocoReport).configureEach {
    reports {
        xml.required = true
        html.required = true
    }
    classDirectories.setFrom(files(classDirectories.files.collect {
        fileTree(dir: it, exclude: jacocoExcludes)
    }))
}

tasks.withType(JacocoCoverageVerification).configureEach {
    violationRules {
        rule {
            limit {
                counter = 'LINE'
                value = 'COVEREDRATIO'
                minimum = 0.8
            }
            limit {
                counter = 'BRANCH'
                value = 'COVEREDRATIO'
                minimum = 0.8
            }
        }
    }
    classDirectories.setFrom(files(classDirectories.files.collect {
        fileTree(dir: it, exclude: jacocoExcludes)
    }))
}
